galaxy_info:
  author: a118n
  role_name: pki_ca
  namespace: a118n
  description: Generate self-signed CA certificate
  license: MIT
  min_ansible_version: "2.1"
  platforms:
    - name: Debian
      versions:
        - bookworm
    - name: EL
      versions:
        - "8"
        - "9"
    - name: Fedora
      versions:
        - "37"
        - "38"
  galaxy_tags: []
dependencies: []
