galaxy_info:
  author: a118n
  role_name: pki_ca
  namespace: a118n
  description: Generate self-signed CA certificate
  license: MIT
  min_ansible_version: "2.1"
  platforms:
    - name: Fedora
      versions:
        - "36"
        - "37"
        - "38"
        - "39"
  galaxy_tags: []
dependencies: []
