---
- name: Check if cilium repo exists
  ansible.builtin.shell:
    cmd: set -o pipefail && helm repo list | grep cilium
    executable: /usr/bin/bash
  changed_when: false
  ignore_errors: true
  register: cni_cilium_repo_exists

- name: Add cilium repo
  ansible.builtin.command:
    cmd: helm repo add cilium https://helm.cilium.io/
  register: cni_cilium_repo_added
  changed_when: cni_cilium_repo_added.rc == 0
  when: cni_cilium_repo_exists.rc != 0

- name: Check if cilium is deployed
  ansible.builtin.shell:
    cmd: set -o pipefail && helm list -n kube-system | grep cilium
    executable: /usr/bin/bash
  changed_when: false
  ignore_errors: true
  register: cni_cilium_deployment_exists
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf

- name: Deploy cilium
  ansible.builtin.command:
    cmd: helm install cilium cilium/cilium --version {{ cilium_version }} --namespace kube-system
  register: cni_cilium_deployed
  changed_when: cni_cilium_deployed.rc == 0
  when: cni_cilium_deployment_exists.rc != 0
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf

- name: Deploy hubble
  ansible.builtin.command:
    cmd: helm upgrade cilium cilium/cilium --version {{ cilium_version }} --namespace kube-system --reuse-values --set hubble.relay.enabled=true --set hubble.ui.enabled=true --set hubble.tls.auto.enabled=true --set hubble.tls.auto.method=helm --set hubble.tls.auto.certValidityDuration=1095
  register: cni_cilium_hubble_deployed
  changed_when: cni_cilium_hubble_deployed.rc == 0
  when: cni_cilium_deployment_exists.rc != 0
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf

- name: Install cilium-cli
  ansible.builtin.shell:
    cmd: |
      CILIUM_CLI_VERSION=$(curl -s https://raw.githubusercontent.com/cilium/cilium-cli/master/stable.txt)
      CLI_ARCH=amd64
      if [ "$(uname -m)" = "aarch64" ]; then CLI_ARCH=arm64; fi
      curl -L --fail --remote-name-all https://github.com/cilium/cilium-cli/releases/download/${CILIUM_CLI_VERSION}/cilium-linux-${CLI_ARCH}.tar.gz{,.sha256sum}
      sha256sum --check cilium-linux-${CLI_ARCH}.tar.gz.sha256sum
      sudo tar xzvfC cilium-linux-${CLI_ARCH}.tar.gz /usr/local/bin
      rm -f cilium-linux-${CLI_ARCH}.tar.gz{,.sha256sum}
    executable: /usr/bin/bash
    creates: /usr/local/bin/cilium

- name: Install hubble-cli
  ansible.builtin.shell:
    cmd: |
      export HUBBLE_VERSION=$(curl -s https://raw.githubusercontent.com/cilium/hubble/master/stable.txt)
      HUBBLE_ARCH=amd64
      if [ "$(uname -m)" = "aarch64" ]; then HUBBLE_ARCH=arm64; fi
      curl -L --fail --remote-name-all https://github.com/cilium/hubble/releases/download/$HUBBLE_VERSION/hubble-linux-${HUBBLE_ARCH}.tar.gz{,.sha256sum}
      sha256sum --check hubble-linux-${HUBBLE_ARCH}.tar.gz.sha256sum
      sudo tar xzvfC hubble-linux-${HUBBLE_ARCH}.tar.gz /usr/local/bin
      rm -f hubble-linux-${HUBBLE_ARCH}.tar.gz{,.sha256sum}
    creates: /usr/local/bin/hubble
