---
- name: Check if cilium repo exists
  ansible.builtin.shell:
    cmd: set -o pipefail && helm repo list | grep cilium
  changed_when: false
  ignore_errors: true
  register: cni_cilium_repo_exists

- name: Add cilium repo
  ansible.builtin.command:
    cmd: helm repo add cilium https://helm.cilium.io/
  register: cni_cilium_repo_added
  changed_when: cni_cilium_repo_added.rc == 0
  when: cni_cilium_repo_exists.rc != 0

- name: Check if cilium is deployed
  ansible.builtin.shell:
    cmd: set -o pipefail && helm list -n kube-system | grep cilium
  changed_when: false
  ignore_errors: true
  register: cni_cilium_deployment_exists
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf

- name: Deploy cilium
  ansible.builtin.command:
    cmd: helm install cilium cilium/cilium --version 1.13.2 --namespace kube-system
  register: cni_cilium_deployed
  changed_when: cni_cilium_deployed.rc == 0
  when: cni_cilium_deployment_exists.rc != 0
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
