---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: vmsingle-pv
  labels:
    type: local
spec:
  storageClassName: local-storage
  capacity:
    storage: 15Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/k8s/vmsingle_pv"
