---
- name: Include OS-specific variables
  ansible.builtin.include_vars: "{{ ansible_os_family | lower }}.yml"

- name: Generate CA PK
  community.crypto.openssl_privatekey:
    path: "{{ pki_ca_system_pk_path }}/{{ pki_ca_pk_name }}"
    state: present
    owner: root
    group: root
    mode: "0444"

- name: Create CSR for CA certificate
  community.crypto.openssl_csr_pipe:
    privatekey_path: "{{ pki_ca_system_pk_path }}/{{ pki_ca_pk_name }}"
    common_name: "{{ pki_ca_common_name }}"
    use_common_name_for_san: false
    basic_constraints:
      - "CA:TRUE"
    basic_constraints_critical: true
    key_usage:
      - keyCertSign
    key_usage_critical: true
  register: ca_csr

- name: Create self-signed CA certificate from CSR
  community.crypto.x509_certificate:
    path: "{{ pki_ca_system_ca_path }}/{{ pki_ca_cert_name }}"
    csr_content: "{{ ca_csr.csr }}"
    privatekey_path: "{{ pki_ca_system_pk_path }}/{{ pki_ca_pk_name }}"
    selfsigned_not_after: +3650d # 10 years
    provider: selfsigned
  notify: Update CA trust

- name: Set host_os fact
  ansible.builtin.set_fact:
    host_os: "{{ ansible_os_family }}"
