---
- name: Create private key with password protection
  community.crypto.openssl_privatekey:
    path: "/etc/pki/tls/private/{{ pki_ca_pk_name }}"
    owner: root
    group: root
    mode: "0400"

- name: Create certificate signing request (CSR) for CA certificate
  community.crypto.openssl_csr_pipe:
    privatekey_path: "/etc/pki/tls/private/{{ pki_ca_pk_name }}"
    common_name: "{{ pki_ca_common_name }}"
    use_common_name_for_san: false
    basic_constraints:
      - "CA:TRUE"
    basic_constraints_critical: true
    key_usage:
      - keyCertSign
    key_usage_critical: true
  register: ca_csr

- name: Create self-signed CA certificate from CSR
  community.crypto.x509_certificate:
    path: "/etc/pki/ca-trust/source/anchors/{{ pki_ca_cert_name }}"
    csr_content: "{{ ca_csr.csr }}"
    privatekey_path: "/etc/pki/tls/private/{{ pki_ca_pk_name }}"
    provider: selfsigned
  notify: Update CA trust
