ansible_user: root
ansible_ssh_user: root

control_plane_endpoint: cluster.k8s.internal
cilium_version: 1.14.2
cert_manager_version: 1.13.0
haproxy_version: 2.8.3
haproxy_use_ssl: false
haproxy_balance_algorithm: source
haproxy_hash_type: consistent
haproxy_api_backend_servers:
  - node-01.k8s.internal
  - node-02.k8s.internal
  - node-03.k8s.internal
haproxy_ingress_backend_servers:
  - node-04.k8s.internal
  - node-05.k8s.internal
  - node-06.k8s.internal
ingress_nodeport_http: 30080
ingress_nodeport_https: 30443
pki_ca_common_name: k8s.internal Certificate Authority
pki_ca_pk_name: k8s.internal.key
pki_ca_cert_name: k8s.internal.pem
