ansible_user: root
ansible_ssh_user: root
ansible_password: fghbjhb
ansible_ssh_password: fghbjhb
ansible_become_password: fghbjhb

control_plane_endpoint: cluster.k8s.internal
cilium_version: 1.13.3
haproxy_version: 2.8.0
haproxy_use_ssl: false
haproxy_balance_algorithm: source
haproxy_hash_type: consistent
haproxy_backend_servers:
  - { name: master-01.k8s.internal, ip: master-01.k8s.internal:6443 }
  - { name: master-02.k8s.internal, ip: master-02.k8s.internal:6443 }
  - { name: master-03.k8s.internal, ip: master-03.k8s.internal:6443 }
