---
- name: Check if vmetrics repo exists
  ansible.builtin.shell:
    cmd: set -o pipefail && helm repo list | grep victoriametrics
    executable: /usr/bin/bash
  changed_when: false
  ignore_errors: true
  register: vmetrics_repo_exists

- name: Add vmetrics repo
  ansible.builtin.command:
    cmd: helm repo add vm https://victoriametrics.github.io/helm-charts/
  register: vmetrics_repo_added
  changed_when: vmetrics_repo_added.rc == 0
  when: vmetrics_repo_exists.rc != 0

- name: Check if vmetrics is deployed
  ansible.builtin.shell:
    cmd: set -o pipefail && helm list -n monitoring | grep victoria-metrics-k8s-stack
    executable: /usr/bin/bash
  changed_when: false
  ignore_errors: true
  register: vmetrics_deployment_exists
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf

- name: Copy vmsingle-pv.yml
  ansible.builtin.copy:
    src: vmsingle-pv.yml
    dest: /root/vmsingle-pv.yml

- name: Create PV for VMSingle
  ansible.builtin.command:
    cmd: kubectl apply -f vmsingle-pv.yml
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  when: vmetrics_deployment_exists.rc != 0

- name: Copy victoria-metrics-k8s-stack.yml
  ansible.builtin.copy:
    src: victoria-metrics-k8s-stack.yml
    dest: /root/victoria-metrics-k8s-stack.yml

- name: Deploy VMetrics stack
  ansible.builtin.shell:
    cmd: helm upgrade --install victoria-metrics-k8s-stack vm/victoria-metrics-k8s-stack --namespace monitoring --create-namespace --values victoria-metrics-k8s-stack.yml
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  # when: vmetrics_deployment_exists.rc != 0
