galaxy_info:
  author: a118n
  role_name: k8s_node
  namespace: a118n
  description: Basic role for any K8S node
  license: MIT
  min_ansible_version: "2.1"
  platforms:
    - name: Debian
      versions:
        - bookworm
    - name: EL
      versions:
        - "8"
        - "9"
  galaxy_tags: []
dependencies: []
