---
- name: Include OS-specific variables
  ansible.builtin.include_vars: "{{ ansible_os_family | lower }}.yml"

- name: Include OS-specific variables
  ansible.builtin.include_vars: "host_{{ hostvars['localhost']['host_os'] | lower }}.yml"

- name: Copy CA PK
  ansible.builtin.copy:
    src: "{{ pki_ca_rollout_host_system_pk_path }}/{{ pki_ca_pk_name }}"
    dest: "{{ pki_ca_rollout_remote_system_pk_path }}/{{ pki_ca_pk_name }}"
    owner: root
    group: root
    mode: "0440"

- name: Copy CA certificate
  ansible.builtin.copy:
    src: "{{ pki_ca_rollout_host_system_ca_path }}/{{ pki_ca_cert_name }}"
    dest: "{{ pki_ca_rollout_remote_system_ca_path }}/{{ pki_ca_cert_name }}"
    owner: root
    group: root
    mode: "0444"
  notify: Update CA trust
