---
- name: Include OS-specific variables
  ansible.builtin.include_vars: "{{ ansible_os_family | lower }}.yml"

- name: Copy CA certificate
  ansible.builtin.copy:
    src: "/etc/pki/ca-trust/source/anchors/{{ pki_ca_cert_name }}"
    dest: "{{ ca_path }}/{{ pki_ca_cert_name }}"
    owner: root
    group: root
    mode: "0444"
  notify: Update CA trust

- name: Copy CA PK
  ansible.builtin.copy:
    src: "/etc/pki/tls/private/{{ pki_ca_pk_name }}"
    dest: "{{ pk_path }}/{{ pki_ca_pk_name }}"
    owner: root
    group: root
    mode: "0440"
  notify: Update CA trust
