---
haproxy_version: 2.8.0
haproxy_use_ssl: false
haproxy_balance_algorithm: source
haproxy_hash_type: consistent
haproxy_backend_servers:
  - { name: test-srv-03, ip: 192.168.122.47:80 }
  - { name: test-srv-04, ip: 192.168.122.85:80 }
