---
- name: Update packages on all k8s nodes
  hosts: all
  tasks:
    - name: Update system
      ansible.builtin.dnf:
        name: "*"
        state: latest
        update_cache: true
      register: update_result

    - name: Remove unneeded packages
      ansible.builtin.dnf:
        autoremove: true
      register: autoremove_result

    - name: Reboot node
      ansible.builtin.reboot:
      when: update_result.changed or autoremove_result.changed
