---
- name: Provision control plane load balancer
  hosts: k8s-control-plane-lb
  roles:
    - haproxy

- name: Provision k8s nodes
  hosts: k8s-master:k8s-control-plane:k8s-workers
  roles:
    - k8s_node

- name: Provision master node
  hosts: k8s-master
  roles:
    - k8s_master

- name: Install cilium
  hosts: k8s-master
  roles:
    - cni_cilium

- name: Provision control plane nodes
  hosts: k8s-control-plane
  serial: 1
  roles:
    - k8s_control_plane

- name: Provision worker nodes
  hosts: k8s-workers
  roles:
    - k8s_worker
