---
- name: Provision load balancer
  hosts: load-balancer
  roles:
    - haproxy

- name: Provision k8s nodes
  hosts: k8s-master:k8s-control-plane:k8s-workers
  roles:
    - k8s_node

- name: Provision master node
  hosts: k8s-master
  roles:
    - k8s_master

- name: Install cilium
  hosts: k8s-master
  roles:
    - cni_cilium

- name: Provision control plane nodes
  hosts: k8s-control-plane
  serial: 1
  roles:
    - k8s_control_plane

- name: Provision worker nodes
  hosts: k8s-workers
  roles:
    - k8s_worker

- name: Label worker nodes
  hosts: k8s-master
  tasks:
    - name: Label node
      ansible.builtin.command:
        cmd: kubectl label node {{ item }} node-role.kubernetes.io/worker=worker
      environment:
        KUBECONFIG: /etc/kubernetes/admin.conf
      with_items:
        - "{{ groups['k8s-workers'] }}"

- name: Install NGINX Ingress controller
  hosts: k8s-master
  tasks:
    - name: Install
      ansible.builtin.command:
        cmd: helm upgrade --install ingress-nginx ingress-nginx --repo https://kubernetes.github.io/ingress-nginx --namespace ingress-nginx --create-namespace --set controller.service.nodePorts.http={{ ingress_nodeport_http }} --set controller.service.nodePorts.https={{ ingress_nodeport_https }}
      environment:
        KUBECONFIG: /etc/kubernetes/admin.conf

- name: Apply additional manifests
  hosts: localhost
  connection: local
  tasks:
    - name: kubectl apply
      ansible.builtin.command:
        cmd: sleep 20 && kubectl apply -f manifests
