---
- name: Provision k8s nodes
  hosts: all
  roles:
    - k8s_node

- name: Provision master nodes
  hosts: k8s-masters
  roles:
    - k8s_master

- name: Provision worker nodes
  hosts: k8s-workers
  roles:
    - k8s_worker

- name: Install cilium
  hosts: k8s-masters[0]
  roles:
    - cni_cilium
