---
- name: Include OS-specific variables
  ansible.builtin.include_vars: "{{ ansible_os_family | lower }}.yml"

- name: Update system
  ansible.builtin.dnf:
    name: "*"
    state: latest
    update_cache: true
  when: ansible_os_family == "RedHat"
  notify: Reboot

- name: Update system
  ansible.builtin.apt:
    name: "*"
    state: latest
    update_cache: true
  when: ansible_os_family == "Debian"
  notify: Reboot

- name: Remove unneeded packages
  ansible.builtin.dnf:
    autoremove: true
  when: ansible_os_family == "RedHat"
  notify: Reboot

- name: Remove unneeded packages
  ansible.builtin.apt:
    autoremove: true
  when: ansible_os_family == "Debian"
  notify: Reboot

- name: Flush handlers
  ansible.builtin.meta: flush_handlers

- name: Configure hostname
  ansible.builtin.hostname:
    name: "{{ inventory_hostname }}"

- name: Add /etc/hosts entry
  ansible.builtin.lineinfile:
    path: /etc/hosts
    mode: "0644"
    owner: root
    group: root
    line: "{{ ansible_default_ipv4.address }} {{ inventory_hostname }} {{ ansible_hostname }}"

- name: Install required packages
  ansible.builtin.package:
    name: "{{ required_packages }}"
    state: present

- name: Check if swap is active
  ansible.builtin.command:
    cmd: swapon -s
  register: k8s_node_swapon
  changed_when: false

- name: Disable swap
  ansible.builtin.command:
    cmd: swapoff -a
  when: k8s_node_swapon.stdout != ""
  changed_when: true

- name: Remove swap from /etc/fstab
  ansible.posix.mount:
    name: "{{ item }}"
    fstype: swap
    state: absent
  loop:
    - swap
    - none

- name: Configure kernel modules
  ansible.builtin.copy:
    dest: /etc/modules-load.d/k8s.conf
    mode: "0644"
    owner: root
    group: root
    content: |
      overlay
      br_netfilter

- name: Modprobe kernel modules
  community.general.modprobe:
    name: "{{ item }}"
    state: present
  loop:
    - overlay
    - br_netfilter

- name: Add kernel parameters
  ansible.builtin.copy:
    dest: /etc/sysctl.d/k8s.conf
    mode: "0644"
    owner: root
    group: root
    content: |
      net.bridge.bridge-nf-call-iptables = 1
      net.bridge.bridge-nf-call-ip6tables = 1
      net.ipv4.ip_forward = 1
  notify: Apply kernel parameters

- name: Add Docker repo
  ansible.builtin.command:
    cmd: dnf config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
    creates: /etc/yum.repos.d/docker-ce.repo
  when: ansible_os_family == "RedHat"

- name: Add Docker GPG key
  ansible.builtin.shell:
    cmd: set -o pipefail && curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
    creates: /etc/apt/keyrings/docker.gpg
    executable: /usr/bin/bash
  when: ansible_os_family == "Debian"

- name: Add Docker repo
  ansible.builtin.copy:
    dest: /etc/apt/sources.list.d/docker.list
    owner: root
    group: root
    mode: "0644"
    content: |
      deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian bookworm stable
  when: ansible_os_family == "Debian"

- name: Update cache
  ansible.builtin.apt:
    update_cache: true
  when: ansible_os_family == "Debian"

- name: Install containerd
  ansible.builtin.package:
    name: containerd.io
    state: present

- name: Enable and start containerd
  ansible.builtin.systemd:
    name: containerd.service
    state: started
    enabled: true

- name: Copy containerd config
  ansible.builtin.copy:
    src: containerd_config.toml
    dest: /etc/containerd/config.toml
    mode: "0644"
    owner: root
    group: root
  notify: Restart containerd

- name: Flush handlers
  ansible.builtin.meta: flush_handlers

- name: Add kubernetes repo
  ansible.builtin.copy:
    dest: /etc/yum.repos.d/kubernetes.repo
    mode: "0644"
    owner: root
    group: root
    content: |
      [kubernetes]
      name=Kubernetes
      baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-$basearch
      enabled=1
      gpgcheck=1
      gpgkey=https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
      exclude=kubelet kubeadm kubectl
  when: ansible_os_family == "RedHat"

- name: Set SELinux mode to permissive
  ansible.posix.selinux:
    state: permissive
    policy: targeted
  when: ansible_os_family == "RedHat"

- name: Install kubernetes components
  ansible.builtin.dnf:
    name:
      - kubelet
      - kubeadm
      - kubectl
    disable_excludes: kubernetes
    state: present
  when: ansible_os_family == "RedHat"

- name: Add Kubernetes GPG key
  ansible.builtin.shell:
    cmd: set -o pipefail && curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.28/deb/Release.key | gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
    creates: /etc/apt/keyrings/kubernetes-apt-keyring.gpg
    executable: /usr/bin/bash
  when: ansible_os_family == "Debian"

- name: Add Kubernetes repo
  ansible.builtin.copy:
    dest: /etc/apt/sources.list.d/docker.list
    owner: root
    group: root
    mode: "0644"
    content: |
      deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.28/deb/ /
  when: ansible_os_family == "Debian"

- name: Update cache
  ansible.builtin.apt:
    update_cache: true
  when: ansible_os_family == "Debian"

- name: Install kubernetes components
  ansible.builtin.apt:
    name:
      - kubelet
      - kubeadm
      - kubectl
    state: present
  when: ansible_os_family == "Debian"

- name: Hold kubernetes packages
  ansible.builtin.command:
    cmd: apt-mark hold kubelet kubeadm kubectl
  when: ansible_os_family == "Debian"

- name: Enable and start kubelet
  ansible.builtin.systemd:
    name: kubelet.service
    state: started
    enabled: true
