---
- name: Update system
  ansible.builtin.dnf:
    name: "*"
    state: latest
    update_cache: true
  notify: Reboot

- name: Remove unneeded packages
  ansible.builtin.dnf:
    autoremove: true
  notify: Reboot

- name: Flush handlers
  ansible.builtin.meta: flush_handlers

- name: Configure hostname
  ansible.builtin.hostname:
    name: "{{ ansible_nodename }}"
    use: systemd

- name: Add /etc/hosts entry
  ansible.builtin.lineinfile:
    path: /etc/hosts
    mode: "0644"
    owner: root
    group: root
    line: "{{ ansible_default_ipv4.address }} {{ ansible_nodename }} {{ ansible_hostname }}"

- name: Install required packages
  ansible.builtin.dnf:
    name:
      - tar
      - git
    state: present
    update_cache: true

- name: Check if swap is active
  ansible.builtin.command:
    cmd: swapon -s
  register: k8s_node_swapon
  changed_when: false

- name: Disable swap
  ansible.builtin.command:
    cmd: swapoff -a
  when: k8s_node_swapon.stdout != ""
  changed_when: true

- name: Remove swap from /etc/fstab
  ansible.posix.mount:
    name: "{{ item }}"
    fstype: swap
    state: absent
  loop:
    - swap
    - none

- name: Disable firewalld
  ansible.builtin.systemd:
    name: firewalld
    state: stopped
    enabled: false

- name: Configure kernel modules
  ansible.builtin.copy:
    dest: /etc/modules-load.d/k8s.conf
    mode: "0644"
    owner: root
    group: root
    content: |
      overlay
      br_netfilter

- name: Modprobe kernel modules
  community.general.modprobe:
    name: "{{ item }}"
    state: present
  loop:
    - overlay
    - br_netfilter

- name: Add kernel parameters
  ansible.builtin.copy:
    dest: /etc/sysctl.d/k8s.conf
    mode: "0644"
    owner: root
    group: root
    content: |
      net.bridge.bridge-nf-call-iptables = 1
      net.bridge.bridge-nf-call-ip6tables = 1
      net.ipv4.ip_forward = 1
  notify: Apply kernel parameters

- name: Add docker repo
  ansible.builtin.command:
    cmd: dnf config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
    creates: /etc/yum.repos.d/docker-ce.repo

- name: Install containerd
  ansible.builtin.dnf:
    name: containerd
    state: present

- name: Enable and start containerd
  ansible.builtin.systemd:
    name: containerd.service
    state: started
    enabled: true

- name: Copy containerd config
  ansible.builtin.copy:
    src: containerd_config.toml
    dest: /etc/containerd/config.toml
    mode: "0644"
    owner: root
    group: root
  notify: Restart containerd

- name: Add kubernetes repo
  ansible.builtin.copy:
    dest: /etc/yum.repos.d/kubernetes.repo
    mode: "0644"
    owner: root
    group: root
    content: |
      [kubernetes]
      name=Kubernetes
      baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-$basearch
      enabled=1
      gpgcheck=1
      gpgkey=https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
      exclude=kubelet kubeadm kubectl

- name: Set SELinux mode to permissive
  ansible.posix.selinux:
    state: permissive
    policy: targeted

- name: Install kubernetes components
  ansible.builtin.dnf:
    name:
      - kubelet
      - kubeadm
      - kubectl
    disable_excludes: kubernetes
    state: present

- name: Enable and start kubelet
  ansible.builtin.systemd:
    name: kubelet.service
    state: started
    enabled: true
