---
- name: Install required packages
  ansible.builtin.dnf:
    name:
      - tar
    state: present
    update_cache: true

- name: Disable swap
  ansible.builtin.shell: |
    swapoff -a

- name: Remove swap from /etc/fstab
  ansible.posix.mount:
    name: "{{ item }}"
    fstype: swap
    state: absent
  loop:
    - swap
    - none

- name: Disable firewalld
  ansible.builtin.systemd:
    name: firewalld
    state: stopped
    enabled: false

- name: Configure kernel modules
  ansible.builtin.copy:
    dest: /etc/modules-load.d/k8s.conf
    mode: "0644"
    owner: root
    group: root
    content: |
      overlay
      br_netfilter

- name: Modprobe kernel modules
  community.general.modprobe:
    name: "{{ item }}"
    state: present
  loop:
    - overlay
    - br_netfilter

- name: Add kernel parameters
  ansible.builtin.copy:
    dest: /etc/sysctl.d/k8s.conf
    mode: "0644"
    owner: root
    group: root
    content: |
      net.bridge.bridge-nf-call-iptables  = 1
      net.bridge.bridge-nf-call-ip6tables = 1
      net.ipv4.ip_forward                 = 1
  notify: Apply kernel parameters

- name: Add kernel parameters for cilium
  ansible.builtin.copy:
    dest: /etc/sysctl.d/cilium.conf
    mode: "0644"
    owner: root
    group: root
    content: |
      CONFIG_BPF=y
      CONFIG_BPF_SYSCALL=y
      CONFIG_NET_CLS_BPF=y
      CONFIG_BPF_JIT=y
      CONFIG_NET_CLS_ACT=y
      CONFIG_NET_SCH_INGRESS=y
      CONFIG_CRYPTO_SHA1=y
      CONFIG_CRYPTO_USER_API_HASH=y
      CONFIG_CGROUPS=y
      CONFIG_CGROUP_BPF=y
      CONFIG_PERF_EVENTS=y
      CONFIG_NETFILTER_XT_SET=m
      CONFIG_IP_SET=m
      CONFIG_IP_SET_HASH_IP=m
  notify: Apply kernel parameters

- name: Add docker repo
  ansible.builtin.command:
    cmd: dnf config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
    creates: /etc/yum.repos.d/docker-ce.repo

- name: Install containerd
  ansible.builtin.dnf:
    name: containerd
    state: present

- name: Enable and start containerd
  ansible.builtin.systemd:
    name: containerd.service
    state: started
    enabled: true

- name: Copy containerd config
  ansible.builtin.copy:
    src: containerd_config.toml
    dest: /etc/containerd/config.toml
    mode: "0644"
    owner: root
    group: root
  notify: Restart containerd

- name: Add kubernetes repo
  ansible.builtin.copy:
    dest: /etc/yum.repos.d/kubernetes.repo
    mode: "0644"
    owner: root
    group: root
    content: |
      [kubernetes]
      name=Kubernetes
      baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-$basearch
      enabled=1
      gpgcheck=1
      gpgkey=https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
      exclude=kubelet kubeadm kubectl

- name: Disable selinux
  ansible.posix.selinux:
    state: permissive
    policy: targeted

- name: Install kubernetes components
  ansible.builtin.dnf:
    name:
      - kubelet
      - kubeadm
      - kubectl
    disable_excludes: kubernetes
    state: present

- name: Enable and start kubelet
  ansible.builtin.systemd:
    name: kubelet.service
    state: started
    enabled: true
