---
- name: Apply kernel parameters
  ansible.builtin.command:
    cmd: sysctl --system

- name: Restart HAProxy
  ansible.builtin.systemd:
    name: haproxy.service
    state: restarted
    daemon_reload: true
