---
- name: Join cluster
  ansible.builtin.command:
    cmd: "kubeadm join {{ control_plane_endpoint }}:6443 --token {{ hostvars['master-01.k8s.internal']['k8s_master_join_token'][0] }} --discovery-token-ca-cert-hash {{ hostvars['master-01.k8s.internal']['k8s_master_discovery_token_ca_cert_hash'][0] }} --control-plane --certificate-key {{ hostvars['master-01.k8s.internal']['k8s_master_certificate_key'][0] }}"
    creates: /var/lib/kubelet/config.yaml
  when: control_plane_endpoint is defined and hostvars['master-01.k8s.internal']['k8s_master_join_token'] is defined and hostvars['master-01.k8s.internal']['k8s_master_discovery_token_ca_cert_hash'] is defined and hostvars['master-01.k8s.internal']['k8s_master_certificate_key'] is defined
