---
- name: Copy kubeadm config
  ansible.builtin.template:
    src: kubeadm.yml.j2
    dest: /root/kubeadm.yml
    owner: root
    group: root
    mode: "0640"

- name: Initialize control plane
  ansible.builtin.command:
    cmd: kubeadm init --config /root/kubeadm.yml --upload-certs
    creates: /var/lib/kubelet/config.yaml
  register: k8s_master_init_result

- name: Extract token
  ansible.builtin.set_fact:
    k8s_master_join_token: "{{ k8s_master_init_result.stdout | regex_search('--token\\s(\\S*)', '\\1') }}"

- name: Extract CA cert hash
  ansible.builtin.set_fact:
    k8s_master_discovery_token_ca_cert_hash: "{{ k8s_master_init_result.stdout | regex_search('--discovery-token-ca-cert-hash\\s(\\S*)', '\\1') }}"

- name: Extract certificate key
  ansible.builtin.set_fact:
    k8s_master_certificate_key: "{{ k8s_master_init_result.stdout | regex_search('--certificate-key\\s(\\S*)', '\\1') }}"

- name: Show token
  ansible.builtin.debug:
    var: k8s_master_join_token

- name: Show CA cert hash
  ansible.builtin.debug:
    var: k8s_master_discovery_token_ca_cert_hash

- name: Show certificate key
  ansible.builtin.debug:
    var: k8s_master_certificate_key

- name: Populate host OS kubeconfig
  ansible.builtin.fetch:
    src: /etc/kubernetes/admin.conf
    dest: ~/.kube/config
    flat: true

- name: Create .kube directory
  ansible.builtin.file:
    path: /root/.kube/
    state: directory
    owner: root
    group: root
    mode: "0750"

- name: Populate local kubeconfig
  ansible.builtin.copy:
    src: /etc/kubernetes/admin.conf
    dest: /root/.kube/config
    remote_src: true
    owner: root
    group: root
    mode: "0640"

- name: Install helm (1/2)
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
    dest: /root/get_helm.sh
    mode: "0700"
    owner: root
    group: root

- name: Install helm (2/2)
  ansible.builtin.shell:
    cmd: /root/get_helm.sh
    executable: /usr/bin/bash
    creates: /usr/local/bin/helm
